### ISSUE TITLE
Local "type: file" source install with relative path fails when deck is not in current working directory

### ISSUE THREAD

**Issue by buschNT** [Getdeck/getdeck#54]
The following deck.yaml can only be installed successfully when `deck get` is called from the folder of the deck file. Something like: `deck get /home/user/test/deck.yaml` fails with "file not found" error message

```
....


decks:
  - name: my-deck
    sources:
      - type: file
        ref: ./k8s/test.yaml
```
