### ISSUE TITLE
Help Wanted: Disabling Authentication on Kubernetes control plane

### ISSUE THREAD

**Issue by Z02X** [Getdeck/getdeck#94]
I am trying to access my load balancer but the machine I am running this on is not the machine I am accessing with. I am trying to at least for now not deal with authentication and can't seem to find how to disable this. Currently I am using k3s like the first example.

**Comment by Schille** [comment]
Hi @Z02X 
please help me to clarify the question. Do you want to disable authentication for the Kubernetes API in a Getdeck provisioned k3s (k3d?) cluster?

**Comment by Schille** [comment]
Well, maybe this can get you started.

I created a Deckfile (`deck.yaml`) with the following content:
```yaml
version: "1"

cluster:
  provider: k3d
  name: anonymous-cluster
  nativeConfig: # content of the native config file (e.g. https://k3d.io/v5.0.0/usage/configfile/)
    apiVersion: k3d.io/v1alpha4
    kind: Simple
    servers: 1 # same as `--servers 1`
    agents: 1 # same as `--agents 2`
    image: rancher/k3s:v1.22.9-k3s1
    kubeAPI: # same as `--api-port myhost.my.domain:6445` (where the name would resolve to 127.0.0.1)
      hostPort: "40133"
    options:
      k3s:
        extraArgs: # additional arguments passed to the `k3s server|agent` command; same as `--k3s-arg`
          - arg: --kube-apiserver-arg=--anonymous-auth=true
            nodeFilters:
              - server:*

decks:
  - name: anonymous
    namespace: default
    sources:
      - type: file
        content:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: anonymous-role
          rules:
            - apiGroups: [""]
              resources: ["*"]
              verbs: ["*"]
      - type: file
        content:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: anonymous-binding
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: anonymous-role
          subjects:
            - apiGroup: rbac.authorization.k8s.io
              kind: User
              name: system:anonymous
```
I hope the YAML structure did not go broken pasting it here. Please mind the `extraArgs` section in the k3d config.

After running `deck get deck.yaml` (on this file) I was able to curl
`curl -k https://0.0.0.0:40133/api/v1/pods` and it returned all Pods without providing authorization data.

Does this help?
